# Results will be saved to neosr/experiments/results/

name = "test_aether_fused"
model_type = "image"
scale = 2
#use_amp = true
#compile = true

[datasets.test_1]
name = "val_1"
type = "single"
dataroot_lq = '/home/phips/Documents/dataset/PDM/OSISRD/v3/validation/x2'
[val]
#tile = 200

[network_g]
type = "aether_tiny"
#type = "aether_small"
#type = "aether_medium"
#type = "aether_large"
fused_init = true

[path]
pretrain_network_g = '/home/phips/Documents/GitHub/aethernet-train/neosr/experiments/2xaether_tiny_qat/models/release/net_g_7000_int8_converted.pth'
